# Generated by Django 5.0.1 on 2024-01-17 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_point', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-id'], 'verbose_name': 'Punto de Caja', 'verbose_name_plural': 'Punto de Caja'},
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='description',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Caja'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='leftover_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Sobrante'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='missing_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Faltante'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('Opened', 'Aperturado'), ('Closed', 'Cerrado')], default='Opened', max_length=15),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_type', models.CharField(choices=[('Opening', 'Apertura'), ('Income', 'Ingreso'), ('Exit', 'Salida'), ('Expense', 'Gasto'), ('Closing', 'Cierre')], default='Opening', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box_point.cashregister', verbose_name='Punto de Caja')),
            ],
            options={
                'verbose_name': 'Movimiento por Caja',
                'verbose_name_plural': 'Movimientos por Caja',
                'ordering': ['-created_at'],
            },
        ),
    ]
