# Generated by Django 5.0.1 on 2024-01-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_point', '0002_alter_cashregister_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmovement',
            name='amount',
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='exit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Egreso'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingreso'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
