# Generated by Django 5.0.1 on 2024-01-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_point', '0003_remove_cashmovement_amount_cashmovement_exit_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipo de Gasto',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='cashmovement',
            options={'ordering': ['-id'], 'verbose_name': 'Movimiento por Caja', 'verbose_name_plural': 'Movimientos por Caja'},
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='cash_type',
            field=models.CharField(choices=[('Opening', 'Apertura'), ('Income', 'Ingreso'), ('Exit', 'Salida'), ('Expense', 'Gasto'), ('Closing', 'Cierre')], default='Opening', max_length=15, verbose_name='T. Movimiento'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Monto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='box_point.expensetype', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Gastos',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-id'],
            },
        ),
    ]
