# Generated by Django 5.0.1 on 2024-01-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_point', '0004_expensetype_alter_cashmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre:'),
            preserve_default=False,
        ),
    ]
