# Generated by Django 5.0.1 on 2024-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_point', '0005_alter_expensetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='type_operation',
            field=models.CharField(choices=[('Opening', 'Apertura de Caja'), ('Sale', 'Venta'), ('Purchase', 'Compra'), ('Expense', 'Gasto'), ('Income', 'Ingreso'), ('Withdrawal', 'Retiro'), ('Transfer', 'Transferencia'), ('Payment', 'Pago'), ('Collection', 'Cobro'), ('Refund', 'Devolución'), ('Adjustment', 'Ajuste'), ('Deposit', 'Depósito'), ('Cash_Withdrawal', 'Retiro de efectivo'), ('Invoice_Payment', 'Pago de factura'), ('Income_Receipt', 'Recibo de ingreso'), ('Bank_Transfer', 'Transferencia bancaria')], default='Adjustment', max_length=30, verbose_name='Operación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='cash_type',
            field=models.CharField(choices=[('Opening', 'Apertura'), ('Income', 'Ingreso'), ('Exit', 'Salida'), ('Expense', 'Gasto'), ('Closing', 'Cierre')], default='Opening', max_length=30, verbose_name='T. Movimiento'),
        ),
    ]
