# Generated by Django 5.0.1 on 2024-03-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_point', '0006_cashmovement_type_operation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashregister',
            old_name='leftover_amount',
            new_name='difference_amount',
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='missing_amount',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ganancia Neto'),
        ),
    ]
