# Generated by Django 5.0.1 on 2024-03-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='amount_won',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
