# Generated by Django 5.0.1 on 2024-03-14 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_point', '0006_cashmovement_type_operation_and_more'),
        ('transactions', '0002_saledetail_amount_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='box_point.cashregister', verbose_name='Punto de Caja'),
            preserve_default=False,
        ),
    ]
