# Generated by Django 5.0.1 on 2024-03-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_saledetail_cant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='cant',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=9),
        ),
    ]
