# Generated by Django 5.0.1 on 2024-03-12 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_provider_created_at_provider_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='purchase',
            name='date_voucher',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de comprobante'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='receipt_type',
            field=models.CharField(choices=[('Ticket', 'Boleta'), ('bill', 'Factura')], default=1, max_length=50, verbose_name='Tipo de Comprobante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='serie',
            field=models.CharField(default=21, max_length=8, unique=True, verbose_name='Serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='number',
            field=models.CharField(max_length=8, unique=True, verbose_name='Número de Serie'),
        ),
    ]
