# Generated by Django 5.0.1 on 2024-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_remove_purchase_date_joined_purchase_date_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='igv_cal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
