# Generated by Django 5.0.1 on 2024-03-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_igv_cal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='dscto',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='price',
            new_name='sale_price',
        ),
    ]
