# Generated by Django 5.0.1 on 2024-03-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_rename_dscto_purchasedetail_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='number',
            field=models.CharField(max_length=8, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='serie',
            field=models.CharField(max_length=8, verbose_name='Serie'),
        ),
    ]
