# Generated by Django 5.0.1 on 2024-03-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_alter_purchase_number_alter_purchase_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='description',
            new_name='description_purchase',
        ),
    ]
