# Generated by Django 5.0.1 on 2024-03-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_rename_description_purchase_description_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='cant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
