# Generated by Django 5.0.1 on 2024-01-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Apertura')),
                ('opening_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Apertura')),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de Cierre')),
                ('closing_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('status', models.CharField(choices=[('Apening', 'Apertura'), ('Closed', 'Cerrado')], default='Apening', max_length=15)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Abrió')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-id'],
            },
        ),
    ]
