# Generated by Django 5.0.1 on 2024-01-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_cashregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
