# Generated by Django 5.0.1 on 2024-01-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_cashregister_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashregister',
            old_name='opened_by',
            new_name='user',
        ),
    ]
