# Generated by Django 5.0.1 on 2024-01-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_saledetail_sale_remove_saledetail_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashRegister',
        ),
    ]
