# Generated by Django 5.0.1 on 2024-03-12 09:55

import import_export.widgets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_delete_cashregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKeyWidgetWithCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(import_export.widgets.ForeignKeyWidget, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Código Barra'),
        ),
    ]
