# Generated by Django 5.0.1 on 2024-03-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Stock'),
        ),
    ]
