# Generated by Django 5.0.1 on 2024-03-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kilo',
            field=models.BooleanField(default=False, verbose_name='¿Es por Kilo?'),
        ),
    ]
