# Generated by Django 5.0.1 on 2024-03-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_product_kilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Stock'),
        ),
    ]
